elongo/elongo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from elongoApp import views

urlpatterns = [
    path('elongoApp/', include('elongoApp.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

elongo/elongoApp/urls.py
from django.urls import path

from . import views

app_name = 'elongoApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('city/new', views.new_city, name='new_city'),
    path('city/list', views.list_city, name='list_city'),
    path('comparison', views.comparison, name='comparison'),
    path('city/list', views.list_city, name='list_city'),
    path('city/details/<int:city_id>', views.city_details, name='city_details'),
    path('electricData/new', views.new_electric_data, name='new_electric_data'),
    path('electricData/list', views.list_electric_data, name='list_electric_data'),
    path('city/details/<int:city_id>/<int:year>', views.city_details_year, name='city_details_year'),
    path('pie_chart', views.pie_chart, name='pie_chart'),

]

elongo/elongoApp/forms.py
from django import forms

from .models import *


class ElectricDataForm(forms.Form):
	city = forms.ModelChoiceField(queryset=City.objects.all(), required=True)
	year = forms.IntegerField(label='Year', min_value=0, required=True)
	population = forms.IntegerField(label='Population', min_value=0, required=True)
	coal = forms.IntegerField(label='Coal (GWh)', min_value=0, required=True)
	natural_gas = forms.IntegerField(label='Natural gas (GWh)', min_value=0, required=True)
	petroleum = forms.IntegerField(label='Petroleum (GWh)', min_value=0, required=True)
	conv_hydro = forms.IntegerField(label='Conv hydro (GWh)', min_value=0, required=True)
	ps_hydro = forms.IntegerField(label='Ps hydro (GWh)', min_value=0, required=True)
	nuclear = forms.IntegerField(label='Nuclear (GWh)', min_value=0, required=True)
	net_imports = forms.IntegerField(label='Net imports (GWh)', min_value=0, required=True)
	other = forms.IntegerField(label='Other (GWh)', min_value=0, required=True)
	waste = forms.IntegerField(label='Waste (GWh)', min_value=0, required=True)
	landfill_gas = forms.IntegerField(label='Landfill gas (GWh)', min_value=0, required=True)
	wood = forms.IntegerField(label='Wood (GWh)', min_value=0, required=True)
	wind = forms.IntegerField(label='Wind (GWh)', min_value=0, required=True)
	solar = forms.IntegerField(label='Solar (GWh)', min_value=0, required=True)
	total = forms.IntegerField(label='Total (GWh)', min_value=0, required=True)

	def save(self, creator):
		electric_data = ElectricData()
		electric_data.city = self.cleaned_data['city']
		electric_data.creator = creator
		electric_data.year = self.cleaned_data['year']
		electric_data.coal = self.cleaned_data['coal']
		electric_data.natural_gas = self.cleaned_data['natural_gas']
		electric_data.petroleum = self.cleaned_data['petroleum']
		electric_data.conv_hydro = self.cleaned_data['conv_hydro']
		electric_data.ps_hydro = self.cleaned_data['ps_hydro']
		electric_data.nuclear = self.cleaned_data['nuclear']
		electric_data.net_imports = self.cleaned_data['net_imports']
		electric_data.other = self.cleaned_data['other']
		electric_data.waste = self.cleaned_data['waste']
		electric_data.landfill_gas = self.cleaned_data['landfill_gas']
		electric_data.wood = self.cleaned_data['wood']
		electric_data.wind = self.cleaned_data['wind']
		electric_data.solar = self.cleaned_data['solar']
		electric_data.total = self.cleaned_data['total']
		electric_data.population = self.cleaned_data['population']
		electric_data.save()
		return electric_data


class CityForm(forms.ModelForm):
	class Meta:
		model = City
		fields = ('name', 'country', 'continent')


class ComparisonForm(forms.Form):
	CHOICES = ((None, '----------'), ('coal', 'Coal'), ('natural_gas', 'Natural gas'),
			   ('petroleum', 'Petroleum'), ('conv_hydro', 'Conv hydro'),
			   ('ps_hydro', 'Ps hydro'), ('nuclear', 'Nuclear'), ('net_imports', 'Net imports'),
			   ('other', 'Other'),
			   ('waste', 'Waste'), ('landfill_gas', 'Landfill gas'), ('wood', 'Wood'), ('wind', 'Wind'),
			   ('solar', 'Solar'),
			   ('total', 'Total'))

	city = forms.ModelChoiceField(queryset=City.objects.all(), required=True)
	field_1 = forms.ChoiceField(choices=CHOICES, required=True)
	field_2 = forms.ChoiceField(choices=CHOICES, required=False)

class PieChartForm(forms.Form):
	CHOICES = (('1920', '1920'),
			   ('1921', '1921'),
			   ('1922', '1922'),
			   ('1923', '1923'),
			   ('1924', '1924'),
			   ('1925', '1925'),
			   ('1926', '1926'),
			   ('1927', '1927'),
			   ('1928', '1928'),
			   ('1929', '1929'),
			   ('1930', '1930'),
			   ('1931', '1931'),
			   ('1932', '1932'),
			   ('1933', '1933'),
			   ('1934', '1934'),
			   ('1935', '1935'),
			   ('1936', '1936'),
			   ('1937', '1937'),
			   ('1938', '1938'),
			   ('1939', '1939'),
			   ('1940', '1940'),
			   ('1941', '1941'),
			   ('1942', '1942'),
			   ('1943', '1943'),
			   ('1944', '1944'),
			   ('1945', '1945'),
			   ('1946', '1946'),
			   ('1947', '1947'),
			   ('1948', '1948'),
			   ('1949', '1949'),
			   ('1950', '1950'),
			   ('1951', '1951'),
			   ('1952', '1952'),
			   ('1953', '1953'),
			   ('1954', '1954'),
			   ('1955', '1955'),
			   ('1956', '1956'),
			   ('1957', '1957'),
			   ('1958', '1958'),
			   ('1959', '1959'),
			   ('1960', '1960'),
			   ('1961', '1961'),
			   ('1962', '1962'),
			   ('1963', '1963'),
			   ('1964', '1964'),
			   ('1965', '1965'),
			   ('1966', '1966'),
			   ('1967', '1967'),
			   ('1968', '1968'),
			   ('1969', '1969'),
			   ('1970', '1970'),
			   ('1971', '1971'),
			   ('1972', '1972'),
			   ('1973', '1973'),
			   ('1974', '1974'),
			   ('1975', '1975'),
			   ('1976', '1976'),
			   ('1977', '1977'),
			   ('1978', '1978'),
			   ('1979', '1979'),
			   ('1980', '1980'),
			   ('1981', '1981'),
			   ('1982', '1982'),
			   ('1983', '1983'),
			   ('1984', '1984'),
			   ('1985', '1985'),
			   ('1986', '1986'),
			   ('1987', '1987'),
			   ('1988', '1988'),
			   ('1989', '1989'),
			   ('1990', '1990'),
			   ('1991', '1991'),
			   ('1992', '1992'),
			   ('1993', '1993'),
			   ('1994', '1994'),
			   ('1995', '1995'),
			   ('1996', '1996'),
			   ('1997', '1997'),
			   ('1998', '1998'),
			   ('1999', '1999'),
			   ('2000', '2000'),
			   ('2001', '2001'),
			   ('2002', '2002'),
			   ('2003', '2003'),
			   ('2004', '2004'),
			   ('2005', '2005'),
			   ('2006', '2006'),
			   ('2007', '2007'),
			   ('2008', '2008'),
			   ('2009', '2009'),
			   ('2010', '2010'),
			   ('2011', '2011'),
			   ('2012', '2012'),
			   ('2013', '2013'),
			   ('2014', '2014'),
			   ('2015', '2015'),
			   ('2016', '2016'),
			   ('2017', '2017'),
			   ('2018', '2018'),
			   ('2019', '2019'))

	city = forms.ModelChoiceField(queryset=City.objects.all(), required=True)
	year = forms.ChoiceField(choices=CHOICES, required=True)

elongo/elongoApp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import *
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.offline as opy
from .forms import *
import datetime

# Create your views here.


def index(request):

    electric_data = ElectricData.objects.all().order_by('year')

    x = [datetime.datetime(year=ed.year, month=1, day=1) for ed in electric_data]
    coal_y = [ed.coal for ed in electric_data]
    petroleum_y = [ed.petroleum for ed in electric_data]

    coal = go.Scatter(
        x=x,
        y=coal_y,
        name="Coal",
        line=dict(color='#17BECF'),
        opacity=0.8)

    petroleum = go.Scatter(
        x=x,
        y=petroleum_y,
        name="Petroleum",
        line=dict(color='#7F7F7F'),
        opacity=0.8)

    data = [coal, petroleum]

    layoutComp = dict(
        title='Coal/petroleum electricity generation comparison',
        xaxis=dict(
            rangeselector=dict(
                buttons=list([
                    dict(count=1,
                         label='1y',
                         step='year',
                         stepmode='backward'),
                    dict(count=5,
                         label='5y',
                         step='year',
                         stepmode='backward'),
                    dict(step='all')
                ])
            ),
            rangeslider=dict(
                visible=True
            ),
            type='date'
        )
    )


    figComp = dict(data=data, layout=layoutComp)
    divComp = opy.plot(figComp, auto_open=False, output_type='div')


    # This is for not comparing grapth
    layout = dict(
        title='Electricity generation with coal',
        xaxis=dict(
            rangeselector=dict(
                buttons=list([
                    dict(count=1,
                         label='1y',
                         step='year',
                         stepmode='backward'),
                    dict(count=5,
                         label='5y',
                         step='year',
                         stepmode='backward'),
                    dict(step='all')
                ])
            ),
            rangeslider=dict(
                visible=True
            ),
            type='date'
        )
    )
    fig = dict(data=[coal], layout=layout)
    div = opy.plot(fig, auto_open=False, output_type='div')
    # py.iplot(fig)

    return render(request, 'elongoApp/index.html', {'graphComp': divComp, 'graph': div})


def to_unix_time(dt):
    epoch = datetime.datetime.utcfromtimestamp(0)
    return (dt - epoch).total_seconds() * 1000


def new_city(request):
    if request.method == "POST":
        form= CityForm(request.POST)
        if form.is_valid():
            city = form.save(commit=False)
            city.save()
            return render(request, 'elongoApp/index.html')
    else:
        form = CityForm()
        return render(request, 'elongoApp/city_form.html', {'form': form})

def list_city(request):
    list = City.objects.all()
    return render(request, 'elongoApp/listCity.html', {'list': list})


def comparison(request):
    if request.method == 'POST':
        form = ComparisonForm(request.POST)
        if form.is_valid():
            graph = generate_graph(form.cleaned_data['city'], form.cleaned_data['field_1'],
                                       form.cleaned_data['field_2'])

            return render(request, 'comparison_form.html', {'form': form, 'graph': graph})

    else:
        form = ComparisonForm()
    return render(request, 'comparison_form.html', {'form': form})


def generate_graph(city, field_1, field_2):
    electric_data = ElectricData.objects.filter(city=city).order_by('year')

    x = [datetime.datetime(year=ed.year, month=1, day=1) for ed in electric_data]
    field_1_y = [getattr(ed, field_1) for ed in electric_data]

    field_1_scatter = go.Scatter(
        x=x,
        y=field_1_y,
        name=field_1.replace("_", " ").capitalize(),
        line=dict(color='#17BECF'),
        opacity=0.8)

    if not field_2:
        layout = dict(
            title="{} electricity generation in the city of {}".format(field_1.replace("_", " ").capitalize(), city),
            xaxis=dict(
                title='Year',
                rangeselector=dict(
                    buttons=list([
                        dict(count=1,
                             label='1y',
                             step='year',
                             stepmode='backward'),
                        dict(count=5,
                             label='5y',
                             step='year',
                             stepmode='backward'),
                        dict(step='all')
                    ])
                ),
                rangeslider=dict(
                    visible=True
                ),
                type='date'
            ),
            yaxis=dict(title='GWh')
        )
        fig = dict(data=[field_1_scatter], layout=layout)
        graph = opy.plot(fig, auto_open=False, output_type='div')
    else:
        field_2_y = [getattr(ed, field_2) for ed in electric_data]

        field_2_scatter = go.Scatter(
            x=x,
            y=field_2_y,
            name=field_2.replace("_", " ").capitalize(),
            line=dict(color='#7F7F7F'),
            opacity=0.8)

        data = [field_1_scatter, field_2_scatter]

        layout = dict(
            title='{}/{} electricity generation comparison in the city of {}'.format(field_1.replace("_", " ").capitalize(), field_2.replace("_", " "), city),
            xaxis=dict(
                title='Year',
                rangeselector=dict(
                    buttons=list([
                        dict(count=1,
                             label='1y',
                             step='year',
                             stepmode='backward'),
                        dict(count=5,
                             label='5y',
                             step='year',
                             stepmode='backward'),
                        dict(step='all')
                    ])
                ),
                rangeslider=dict(
                    visible=True
                ),
                type='date'
            ),
            yaxis=dict(title='GWh')
        )

        fig = dict(data=data, layout=layout)
        graph = opy.plot(fig, auto_open=False, output_type='div')

    return graph


def city_details(request,city_id):
    if city_id:
        city = City.objects.filter(id=city_id).first()
        list_electric_data = ElectricData.objects.filter(city=city).order_by('-year')
        year = None
        average_total_consume = 0
        average_coal_consume=0
        average_natural_gas_consume = 0
        average_petroleum_consume = 0
        average_hydro_consume = 0
        average_nuclear_consume = 0
        average_other_consume = 0
        average_wood_consume = 0
        average_wind_consume = 0
        average_solar_consume = 0
        population = 0

        if len(list_electric_data) > 0:
            count = len(list_electric_data)
            year = list_electric_data.order_by('-total').first().year
            for electric_data in list_electric_data:
                average_total_consume += electric_data.total
                average_coal_consume += electric_data.coal
                average_natural_gas_consume += electric_data.natural_gas
                average_petroleum_consume += electric_data.petroleum
                average_hydro_consume += electric_data.ps_hydro + electric_data.conv_hydro
                average_nuclear_consume += electric_data.nuclear
                average_other_consume += electric_data.other + electric_data.landfill_gas +electric_data.waste +electric_data.net_imports
                average_wood_consume += electric_data.wood
                average_wind_consume += electric_data.wind
                average_solar_consume += electric_data.solar
                population+= electric_data.population


            average_total_consume/=count
            average_natural_gas_consume/=count
            average_petroleum_consume/=count
            average_hydro_consume/=count
            average_nuclear_consume/=count
            average_other_consume/=count
            average_wood_consume/=count
            average_wind_consume/=count
            average_solar_consume/=count
            if population !=0:
                population/=count


    #Total produced average graph
    labels = ['Natural Gas ', 'Petroleum', 'Hydro', 'Nuclear', 'Others', 'Wood', 'Wind','Solar']
    values = [average_natural_gas_consume, average_petroleum_consume, average_hydro_consume, average_nuclear_consume,average_other_consume,
              average_wood_consume,average_wind_consume ,average_solar_consume]
    trace = go.Pie(labels=labels, values=values)
    graph = opy.plot([trace], auto_open=False, output_type='div')

    # Energies
    labels = [ 'Non-renewable energy','Renewable energy', 'Others']
    values = [average_natural_gas_consume + average_petroleum_consume + average_nuclear_consume,
              average_hydro_consume+ average_wood_consume+ average_wind_consume+ average_solar_consume,
              average_other_consume
             ]
    trace = go.Pie(labels=labels, values=values)
    graph2 = opy.plot([trace], auto_open=False, output_type='div')

    #Population by year
    years = list()
    populations = list()

    for ed in list_electric_data.order_by('year'):
        years.append(ed.year)
        populations.append(ed.population)

    data = [go.Bar(
        x=years,
        y=populations
    )]

    graph3 = opy.plot(data, auto_open=False, output_type='div')






    return render(request, 'elongoApp/listElectricData.html', {'graph': graph,
                                                               'graph2': graph2,
                                                               'graph3': graph3,

elongo/elongoApp/templates/elongoApp/city_form.html
{% include 'elongoApp/header_template.html' %}
<body>
{% block content %}
    <br>
    <div class="container" align="center" style="border-style: solid;
  border-width: 1px; border-color: black">
    <br><br>
    <h2>New city</h2>
        <img src="http://dontmakeplansfor2018.com/wsp_images/city.png" height="200" width="300">
        <br><br><br>
    <form method="POST" class="form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary mb-2">Save</button>
    </form>
    </div>
{% endblock %}
{% include 'elongoApp/footer_template.html' %}
</body>

elongo/elongoApp/templates/elongoApp/comparison_form.html
{% include 'elongoApp/header_template.html' %}
<body>
{% block content %}
    <br>
    <div class="container" align="center" style="border-style: solid;
  border-width: 1px; border-color: black">
    <br><br>
    <h2>Compare</h2>
    <form method="POST" class="form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Generate graph!</button>
    </form>
    </div>

    {% if graph %}
        <div class="container" align="center" style="width:900px;height:800px">
            {{ graph|safe }}
        </div>
    {% endif %}
{% endblock %}
{% include 'elongoApp/footer_template.html' %}
</body>

elongo/elongoApp/templates/elongoApp/electric_data_form.html
{% include 'elongoApp/header_template.html' %}
<body>
{% block content %}
    <br>
    <div class="container" align="center" style="border-style: solid;
  border-width: 1px; border-color: black">
    <br><br>
    <h2>New Electric Data</h2>
        <img src="https://www.certificadosenergeticos.com/wp-content/uploads/2014/03/nueva-redacci%C3%B3n-CTE.png" height="200" width="300">
        <br><br><br>
    <form method="POST" class="form">{% csrf_token %}
        {% if error %}
            <div style="display: inline-block; color: red;">
                <p>{{ error }}</p>
            </div><br/><br/>
    {% endif %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Save</button>
    </form>
    </div>
{% endblock %}
{% include 'elongoApp/footer_template.html' %}
</body>

elongo/elongoApp/templates/elongoApp/footer_template.html
<!--<footer class="page-footer font-small blue fixed-bottom bg-primary">
    <div class="footer-copyright py-3" id="time" style="color: #fff; padding-left: 1%; position: absolute"></div>
    <div class="footer-copyright text-center py-3" style="color: #fff;">&copy;
        <script>document.write(new Date().getFullYear())</script>
        Copyright: <a style="text-decoration: none; color: #fff" href="/elongo">Elongo</a>
    </div>
</footer>
<script>
    function updateClock() {
        let now = new Date(), months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August',
                'September', 'October', 'November', 'December'],
            time = now.getHours() + ':' + (now.getMinutes() < 10 ? '0' + now.getMinutes() : now.getMinutes()) + ':' + (now.getSeconds() < 10 ? '0' + now.getSeconds() : now.getSeconds()),
            date = [now.getDate(), months[now.getMonth()], now.getFullYear()].join(' ');

        document.getElementById('time').innerHTML = [date, time].join(', ');

        setTimeout(updateClock, 1000);
    }

    updateClock();
</script> -->

elongo/elongoApp/templates/elongoApp/header_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Elongo</title>
</head>
<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark ">
        <img src="https://creditogranada.com/wp-content/uploads/2018/01/icono-bombilla.png" width="40" height="40">
        <a class="navbar-brand" href="/" style="padding-left: 5px">Elongo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Graphs
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/elongoApp/comparison">Comparison</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/elongoApp/pie_chart">Pie charts</a>

                    </div>
                </li>
                 <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        City
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/elongoApp/city/list">List</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/elongoApp/city/new">New</a>

                    </div>
                </li>
                 <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Electric Data
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/elongoApp/electricData/new">New</a>

                    </div>
                </li>
            </ul>
        </div>

        <div class="navbar-nav flex-row ml-md-auto d-none d-md-flex" style="color: #fff;">{% if user.is_authenticated %}
            <a class="nav-link">{{ user.username }}</a>
            <a class = "btn btn-outline-light" href="{% url 'logout' %}">Logout</a></div>
            {% else %}
            <a class="btn btn-outline-light" href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a>
            {% endif %}
    </nav>
</header>

{#<script>#}
{#    function updateClock() {#}
{#        let now = new Date(), months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August',#}
{#                'September', 'October', 'November', 'December'],#}
{#            time = now.getHours() + ':' + (now.getMinutes() < 10 ? '0' + now.getMinutes() : now.getMinutes()) + ':' + (now.getSeconds() < 10 ? '0' + now.getSeconds() : now.getSeconds()),#}
{#            date = [now.getDate(), months[now.getMonth()], now.getFullYear()].join(' ');#}
{##}
{#        document.getElementById('time').innerHTML = [date, time].join(', ');#}
{##}
{#        setTimeout(updateClock, 1000);#}
{#    }#}
{##}
{#    updateClock();#}
{#</script>#}

elongo/elongoApp/templates/elongoApp/index.html
{% include 'elongoApp/header_template.html' %}
<body >
<img src="https://www.hcenergia.com/img/imagen2.jpg" width="100%" height="80%">
{% include 'elongoApp/footer_template.html' %}
</body>

elongo/elongoApp/templates/elongoApp/listCity.html
{% include 'elongoApp/header_template.html' %}
<body>
<br>
<div align="center"><h1>Cities List</h1>
    <br>
    <img src="https://imagendeciudades.com/wp-content/uploads/2016/09/Imagenes-PNG-de-siluetas-de-ciudades.png"
         width="700" align="center"></div>
<br>

<br>
<table class="table">
    <thead class="table-warning">
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Country</th>
        <th scope="col">Continent</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    {% for city in list %}
        <tr>
            <td scope="row">{{ city.name }}</td>
            <td scope="row">{{ city.country }}</td>
            <td scope="row">{{ city.continent }}</td>
            <td scope="row"><a href="{% url 'elongoApp:city_details' city_id=city.id %}">
                <button type="button" class="btn btn-dark">Details</button></a></td>

        </tr>
    {% empty %}
        <h2> Insufficient user data </h2>
    {% endfor %}
    </tbody>
</table>
<br>
<br>
{% include 'elongoApp/footer_template.html' %}
</body>

elongo/elongoApp/templates/elongoApp/messages_view.html
{% include 'elongoApp/header_template.html' %}
<body>


{% if message %}
    <p class="lead">{{ message }}</p>
{% endif %}

{% include 'elongoApp/footer_template.html' %}
</body>

elongo/elongoApp/templates/elongoApp/pie_chart_form.html
{% include 'elongoApp/header_template.html' %}
<body>
{% block content %}
    <br>
    <div class="container" align="center" style="border-style: solid;
  border-width: 1px; border-color: black">
    <br><br>
    <h2>Compare</h2>
    <form method="POST" class="form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Generate graph!</button>
    </form>
    </div>

    {% if no_data %}
        <h2 class="container" align="center" style="color: red; margin-top: 3%;">
            {{ no_data }}
        </h2>
    {% endif %}

    <div align="center">
        <div class="col-6 col-md-4" style="margin-top: 3%;">
            <h4>{{ title }}</h4></div>
    </div>
    {% if graph %}
        <div class="container" align="center" style="width:600px;height:500px">
            {{ graph|safe }}
        </div>
    {% endif %}
{% endblock %}
{% include 'elongoApp/footer_template.html' %}
</body>